### ISSUE TITLE
Release for Kinetic?

### ISSUE THREAD

**Issue by bmagyar** [swri-robotics/swri_profiler#16]
Hello @gavanderhoorn @pjreed 
Any change for a release of this? I can also do it if I get permissions.

**Comment by gavanderhoorn** [comment]
Not sure why you tagged me @bmagyar :) I'm not involved with this project.

**Comment by pjreed** [comment]
Oh, for some reason I thought we had released this for Indigo/Kinetic already.  Sure, I'll do that soon.

**Comment by pjreed** [comment]
It's been released into Kinetic as of https://github.com/ros/rosdistro/pull/17878, so now it's just waiting on the ROS folks to push a sync to the main repository.

**Comment by bmagyar** [comment]
Sorry about that @gavanderhoorn , it was only the two of you listed in the org and I thought it's better to ask everyone.

Thanks for the release!
