### ISSUE TITLE
Debian Package Release for Ros Noetic?

### ISSUE THREAD

**Issue by Magnusgaertner** [swri-robotics/swri_profiler#25]
@pjreed Is this package planned to be released for ros noetic? 

At this point I want to thank you for this great package! In my opinion it is extremely simple to use and integrate, yet quite powerful :+1: 

Best
Magnus

**Comment by pjreed** [comment]
I hadn't released this because we haven't started using Noetic regularly yet, but I'll go ahead and open a PR: https://github.com/ros/rosdistro/pull/26307

Let me know if it works it Noetic for you!

**Comment by Magnusgaertner** [comment]
Thanks :)
